#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export RBENV_ROOT=/usr/local/var/rbenv

if which brew &> /dev/null; then
  export BYOBU_PREFIX=$(brew --prefix)
fi

# see http://dougblack.io/words/zsh-vi-mode.html
export KEYTIMEOUT=1

export MONO_GAC_PREFIX="/usr/local"
