#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export RBENV_ROOT=/usr/local/var/rbenv

if which brew &> /dev/null; then
  export BYOBU_PREFIX=$(brew --prefix)
fi

# see http://dougblack.io/words/zsh-vi-mode.html
export KEYTIMEOUT=1

export MONO_GAC_PREFIX="/usr/local:$MONO_GAC_PREFIX"

# make ansible not use cowsay
export ANSIBLE_NOCOWS=1

export GOPATH="$HOME/go"
export HAXE_STD_PATH="/usr/local/lib/haxe/std"
export PATH=/Library/Frameworks/Mono.framework/Commands:$HOME/.npm/bin:$PATH:$GOPATH/bin:/usr/local/opt/go/libexec/bin

# BASE16_THEME="3024"
# BASE16_THEME="ir-black"
BASE16_THEME="default-light"

# private env settings
if [[ -s "${ZDOTDIR:-$HOME}/.zshenv_private" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv_private" 
fi

export FZF_DEFAULT_OPTS="--extended --cycle"
export FZF_DEFAULT_COMMAND='
  (git ls-tree -r --name-only HEAD ||
   find * -name ".*" -prune -o -type f -print -o -type l -print) 2> /dev/null'
