#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Custom key bindings
bindkey "\033[1;5D" backward-word
bindkey "\033[1;5C" forward-word
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# Load fzf
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# gulp completion
if which gulp &> /dev/null; then
  eval "$(gulp --completion=zsh)"
fi

# grunt completion
if which grunt &> /dev/null; then
  eval "$(grunt --completion=zsh)"
fi

# More aliases
alias gff="git-flow"

# Fix run-help
case $(type run-help) in
  *alias*) unalias run-help
esac
autoload run-help

if [[ -f ~/.iterm2_shell_integration ]]; then
  source ~/.iterm2_shell_integration.zsh
fi
