#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load fzf
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# gulp completion
if which gulp &> /dev/null; then
  eval "$(gulp --completion=zsh)"
fi
